export const APP_NAME = "EyeAI";
export const COLLEGE = "Sri Muthukumaran Institute of Technology, Chennai";

export const FEATURES = [
  {
    icon: "💧",
    title: "Wet Eye Detection",
    desc: "Corneal moisture level analysis via OpenCV tear film mapping.",
    color: "var(--cyan-bright)",
  },
  {
    icon: "🔴",
    title: "Dry Eye Detection",
    desc: "Surface irregularity and dryness scoring with AI heatmaps.",
    color: "var(--danger)",
  },
  {
    icon: "👁️",
    title: "Real-time Eye Tracking",
    desc: "Sub-frame eyeball movement vector analysis.",
    color: "var(--electric)",
  },
  {
    icon: "🤖",
    title: "LLM Diagnostic Report",
    desc: "Natural language health summary generated by language model.",
    color: "var(--success)",
  },
];

export const STEPS = [
  { n: 1, icon: "📷", title: "Grant Camera Access", desc: "Allow webcam for real-time capture." },
  { n: 2, icon: "🔍", title: "AI Scans Your Eye", desc: "OpenCV + LLM analyzes in real-time." },
  { n: 3, icon: "📋", title: "Get Instant Report", desc: "Detailed diagnosis with severity score." },
  { n: 4, icon: "💊", title: "Recovery Guide", desc: "Personalized treatment steps shown instantly." },
];

export const DRY_RECOVERY = [
  { icon: "💧", title: "Immediate Hydration (Day 1–2)", desc: "Use preservative-free artificial tears every 2–4 hours. Avoid air-conditioned rooms and screen exposure for 30 minutes.", badge: "First Response" },
  { icon: "😴", title: "Rest & Reduce Screen Time (Day 2–5)", desc: "Follow the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds. Blink consciously and frequently.", badge: "Daily Habit" },
  { icon: "🥗", title: "Dietary & Lifestyle Adjustments (Week 1–2)", desc: "Increase Omega-3 intake (flaxseed, fish oil). Stay hydrated with 2–3L water daily. Use a humidifier indoors.", badge: "Nutrition" },
  { icon: "🩺", title: "Medical Consultation (Week 2)", desc: "If symptoms persist, consult an ophthalmologist for prescription eye drops (cyclosporine) or punctal plugs.", badge: "Clinical" },
  { icon: "✅", title: "Prevention & Monitoring (Ongoing)", desc: "Re-scan every 2 weeks using EyeAI. Wear UV-protective sunglasses outdoors. Avoid rubbing your eyes.", badge: "Long-term Care" },
];

export const WET_RECOVERY = [
  { icon: "🧻", title: "Gentle Cleaning (Immediate)", desc: "Clean eye area gently with sterile saline wipes. Do not rub. Avoid contact lenses until condition clears.", badge: "First Response" },
  { icon: "🌡️", title: "Identify the Trigger (Day 1–3)", desc: "Wet eyes can be caused by allergies, blocked tear ducts, or wind exposure. Remove allergens from your environment.", badge: "Root Cause" },
  { icon: "💊", title: "Antihistamine / Allergy Treatment (Day 3–7)", desc: "If allergy-induced, use OTC antihistamine eye drops. Avoid dusty or smoky environments.", badge: "Treatment" },
  { icon: "🩺", title: "Specialist Visit (Week 1–2)", desc: "Persistent watery eyes may indicate dacryostenosis (blocked duct). An ophthalmologist may perform irrigation or surgery.", badge: "Clinical" },
  { icon: "✅", title: "Monitoring & Prevention (Ongoing)", desc: "Re-scan using EyeAI every 2 weeks. Protect eyes from wind/dust. Wear wraparound glasses outdoors.", badge: "Long-term Care" },
];

export const GENERAL_TIPS = [
  { icon: "💻", title: "Reduce blue light exposure", desc: "Use night mode or blue light glasses." },
  { icon: "🌿", title: "Palming technique", desc: "Rub hands warm and cup over closed eyes for 60 seconds." },
  { icon: "🚶", title: "Outdoor time", desc: "30 mins of natural light daily reduces eye strain." },
  { icon: "🥦", title: "Eat for your eyes", desc: "Lutein (spinach), Vitamin A (carrots), Zinc (nuts)." },
  { icon: "💤", title: "Sleep hygiene", desc: "7–8 hours; eyes repair during REM sleep." },
];

export const FAQS = [
  { q: "What causes dry eyes?", a: "Reduced tear production, prolonged screen use, low humidity, ageing, and certain medications can all reduce tear film stability." },
  { q: "Are watery eyes always allergy-related?", a: "No — they can also be caused by blocked tear ducts (dacryostenosis), wind exposure, infections, or even compensatory tearing from dryness." },
  { q: "How accurate is EyeAI?", a: "Our model has a validated accuracy of 98.7% on test datasets. It is designed for screening, not diagnosis." },
  { q: "Can I use EyeAI with contact lenses?", a: "Remove contact lenses before scanning for the most accurate tear-film analysis." },
  { q: "How often should I scan?", a: "Every 2 weeks during a recovery program, or anytime symptoms change." },
];

export const RECENT_SCANS = [
  { date: "2025-04-18", condition: "Dry Eye", severity: "Moderate", score: 78 },
  { date: "2025-04-15", condition: "Normal", severity: "Healthy", score: 96 },
  { date: "2025-04-12", condition: "Wet Eye", severity: "Mild", score: 84 },
  { date: "2025-04-08", condition: "Dry Eye", severity: "Mild", score: 81 },
  { date: "2025-04-04", condition: "Normal", severity: "Healthy", score: 94 },
];

export const WEEKLY_SCANS = [
  { day: "Mon", scans: 3 },
  { day: "Tue", scans: 5 },
  { day: "Wed", scans: 2 },
  { day: "Thu", scans: 6 },
  { day: "Fri", scans: 4 },
  { day: "Sat", scans: 1 },
  { day: "Sun", scans: 3 },
];

export const CONDITION_BREAKDOWN = [
  { name: "Dry Eye", value: 9, color: "#EF4444" },
  { name: "Wet Eye", value: 6, color: "#00C8FF" },
  { name: "Normal", value: 9, color: "#10B981" },
];
